import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "SuperMarketPlace",
    template:"%s | Market"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/public/favicon.ico"></link>
      </head>
      <body
      >
        <header
        >
          <h1 className="flex justify-center items-center pt-7 font-bold text-3xl font-title tracking-wider">Market Place</h1>
          <nav className="flex justify-center border p-3 m-4 border-l-transparent border-r-transparent">
        <ul className="flex flex-row space-x-9">
          <li><Link href="/" className="hover:underline">Home</Link></li>
          <li><Link href="/pages" className="hover:underline">Pages</Link></li>
          <li><Link href="/about" className="hover:underline">About us</Link></li>
          <li><Link href="/offer" className="hover:underline">Offer of the Month</Link></li>
        </ul>
      </nav>
        </header>
        {children}
        <footer
          className="flex justify-center items-center pt-4"
        >
          <p>© 2024 SuperMarketPlace. All Rights Reserved.</p>
        </footer>
      </body>
    </html>
  );
}
