import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "SuperMarketPlace",
    template:"%s | Market"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <header
        className="flex justify-center items-center pt-7 font-bold text-3xl font-title tracking-wider">
          <h1>Market Place</h1>
        </header>
        {children}
        <footer
          className="flex justify-center items-center pt-4"
        >
          <p>© 2024 SuperMarketPlace. All Rights Reserved.</p>
        </footer>
      </body>
    </html>
  );
}
